title: Fuel Lab
description: 車の燃費や整備情報を扱う実験的サイト
baseurl: ""
url: "https://funyapar-fuel-lab.com"
default_ogp_img: "/assets/ogp/default.png"
markdown: kramdown
theme: null
collections:
  about:
    output: true
  tools:
    output: true
  knowledge:
    output: true
  solio:
    output: true
  tags:
    output: true
    permalink: /tags/:name/
  category:
    output: true
    permalink: /category/:name/
plugins:
  - jekyll-sitemap
